import type { PrismaClient } from "../../src/generated/prisma/client";

const articles = [
  {
    title: "Urban Greenery: The Rise of \"Bio-Luminescent\" Smart Parks",
    description: "City planners are ditching traditional streetlights in favor of a glowing alternative. This week, the Department of Urban Development unveiled \"Project Aurora,\" the first public park integrated with bio-engineered flora.",
    content: `Urban Greenery: The Rise of "Bio-Luminescent" Smart Parks\nBy Julian Thorne | Tech & Environment Correspondent\n\nSEATTLE — City planners are ditching traditional streetlights in favor of a glowing alternative. This week, the Department of Urban Development unveiled "Project Aurora," the first public park integrated with bio-engineered flora designed to emit a soft, ambient glow after sundown.\n\nThe initiative uses a specialized, non-invasive protein treatment applied to common ferns and oak trees. During the day, the plants photosynthesize as usual; at night, they provide enough illumination for pedestrian walkways without the need for electricity or copper wiring.\n\nWhy It Matters:\n- Energy Efficiency: Estimated savings of $1.2M annually.\n- Reduced Light Pollution: The "living light" doesn't disrupt local bird migration.\n\n"We aren't just planting trees; we're installing a self-sustaining infrastructure," says Lead Architect Sarah Chen.`,
    categoryName: "Environment",
    imageUrl: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop",
    status: "article",
  },
  {
    title: "The 'Ghost Kitchen' Collapse: Why Virtual Dining is Cooling Off",
    description: "After a meteoric rise during the pandemic, the virtual restaurant industry is facing a harsh reality check as consumers return to physical dining rooms.",
    content: `The 'Ghost Kitchen' Collapse: Why Virtual Dining is Cooling Off\nBy Elena Rodriguez | Business Analyst\n\nCHICAGO — The era of the digital-only restaurant is hitting a major speed bump. Data shows a 25% decline in virtual brand openings this quarter as operational costs and 'delivery fatigue' set in.\n\nIndustry experts suggest that without a physical storefront, brands struggle to build the customer loyalty necessary to survive rising third-party delivery fees. "A brand is more than a logo on an app," says hospitality consultant Mark Vance.\n\nWhat's Next:\n- Consolidation: Larger chains are buying out smaller virtual kitchens.\n- Hybrid Models: Successful digital brands are now seeking small-footprint physical pop-ups to ground their identity.`,
    categoryName: "Business",
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1000&auto=format&fit=crop",
    status: "article",
  },
  {
    title: "Quantum Leap: First Desktop Quantum Computer Hits the Market",
    description: "A startup in Zurich has just released 'Q-Bit 1,' the world's first commercially available quantum processor designed for high-end consumer hardware.",
    content: `Quantum Leap: First Desktop Quantum Computer Hits the Market\nBy Sam Vickers | Tech Reporter\n\nZURICH — The impossible just became a retail reality. For the price of a luxury car, high-end researchers and tech enthusiasts can now own a localized quantum computing unit.\n\nWhile traditional silicon chips use binary bits, the Q-Bit 1 utilizes stable trapped-ion technology. It promises to revolutionize local data encryption and complex molecular modeling for home-based labs.\n\nKey Specs:\n- 5-Qubit Stability: Small but powerful enough for advanced cryptography.\n- Liquid Nitrogen-Free: Uses a proprietary solid-state cooling system.\n\n"This is the ENIAC moment of the 21st century," says CEO Hans Mueller.`,
    categoryName: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1000&auto=format&fit=crop",
    status: "article",
  },
  {
    title: "The Renaissance of Vinyl: Analog Sales Outpace Digital Downloads",
    description: "For the first time in decades, physical record sales have surpassed digital track purchases, driven by a Gen Z obsession with tactile media.",
    content: `The Renaissance of Vinyl: Analog Sales Outpace Digital Downloads\nBy Chloe Sims | Culture Writer\n\nNASHVILLE — In an increasingly cloud-based world, the needle is dropping back on physical media. New reports indicate that vinyl LP sales grew by 18% last year, officially overtaking the revenue generated by individual digital downloads.\n\nCollectors cite 'ownership' and 'intentional listening' as the primary drivers. "You can't hold a stream," says local shop owner Dave Grogan. "A record is an artifact."\n\nMarket Trends:\n- Limited Editions: Colored vinyl and 180g pressings are the top sellers.\n- Hardware Growth: Turntable sales have seen a 12% year-over-year increase.`,
    categoryName: "Lifestyle",
    imageUrl: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?q=80&w=1000&auto=format&fit=crop",
    status: "article",
  },
  {
    title: "Mars Colony Simulation Reaches 500-Day Milestone",
    description: "Six volunteers in the Utah desert have completed a record-breaking isolation study, providing critical data for the upcoming 2030 manned Mars mission.",
    content: `Mars Colony Simulation Reaches 500-Day Milestone\nBy Dr. Aris Thorne | Space & Science\n\nHANKSVILLE — Emerging from a pressurized dome for the first time in over a year, the crew of the 'Red Horizon' simulation celebrated a major victory for space psychology.\n\nThe study focused on the mental toll of delayed communication and closed-loop resource management. Findings suggest that 'interpersonal friction' is a bigger threat to a Mars mission than mechanical failure.\n\nKey Findings:\n- Hydroponic Success: The crew grew 80% of their own leafy greens.\n- Tech Reliability: The 3D-printed habitat structure maintained a perfect seal despite extreme temperature swings.`,
    categoryName: "Science",
    imageUrl: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop",
    status: "article",
  },
  {
    title: "The Rise of 'Deep-Work' Retreats in Northern Europe",
    description: "Companies are ditching traditional offices for week-long focused retreats in secluded forests to combat digital burnout and boost productivity.",
    content: `The Rise of 'Deep-Work' Retreats in Northern Europe\nBy Ingrid Blom | Wellness Correspondent\n\nOSLO — As the 'always-on' culture leads to record burnout, a new trend is emerging: the Silence Sabbatical. Companies are now booking remote cabins in the Norwegian fjords for their developers and creative leads.\n\nThese retreats ban smartphones and Slack for 6 hours a day, allowing for 'deep work'—a state of distraction-free concentration. Initial results show a 30% faster project completion rate compared to the standard office environment.\n\nCore Pillars:\n- Digital Detox: Hardware is checked in at the door.\n- Nature Integration: Meetings take place during forest hikes.\n- Monotasking: One goal per day, zero interruptions.`,
    categoryName: "Health",
    imageUrl: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?q=80&w=1000&auto=format&fit=crop",
    status: "article",
  },
];

export { articles };

export async function seedArticles(
  prisma: PrismaClient,
  userId: number,
  categoryMap: Record<string, number>
): Promise<number[]> {
  const contentArticleIds: number[] = [];
  for (const a of articles) {
    const categoryId = categoryMap[a.categoryName];
    if (categoryId == null) continue;
    const created = await prisma.contentArticle.create({
      data: {
        usersId: userId,
        categoryId,
        title: a.title,
        content: a.content,
        imageUrl: a.imageUrl,
        status: a.status,
      },
    });
    contentArticleIds.push(created.id);
  }
  return contentArticleIds;
}
